on: 
  push:
    paths:
    - 'test.Rmd'
name: RMD Renders
jobs:
  check-rmd:
    runs-on: self-hosted
    container:
      image: ghcr.io/statprog-s1-2020/hw1-docker:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Renders
      run: |
        checklist::check_rmd_renders("test.Rmd")
      shell: Rscript {0}