name: rmd_renders
on: [push] 
jobs:
  check-rmd:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Rmd Rendering
      run:  Rscript -e "rmarkdown::render('test.Rmd')"
