on: 
  push:
    paths:
    - 'test.Rmd'
name: Check RMarkdown Renders
jobs:
  check-rmd:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Renders
      run: |
        checklist::check_rmd_renders("test.Rmd")
      shell: Rscript {0}