on: 
  push:
    paths:
    - 'test.Rmd'
name: Check RMarkdown Renders
jobs:
  knit:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
    - uses: actions/checkout@master
    - name: Check
      run:  Rscript -e "rmarkdown::render('test.Rmd')"
