on: 
  push:
    paths:
    - 'test.Rmd'
name: Check RMarkdown Renders
jobs:
  check: 
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install latex
      run:  |
        tinytex::install_tinytex()
      shell:  Rscript {0}
    - name: Check Renders
      run:  |
        rmarkdown::render('test.Rmd')
      shell:  Rscript {0}